---
output: 
  html_document:
    css: css/style.css
    includes:
      in_header: resizer.html
runtime: shiny_prerendered
---
  
```{r setup, include=FALSE}  
library(tidyverse)
library(janitor)
library(learnr)

here::here()


# Load data
whr15 <- read_csv(here::here("data", "raw", "whr", "WHR2015.csv")) %>% clean_names()
whr16 <- read_csv(here::here("data", "raw", "whr", "WHR2016.csv")) %>% clean_names()
whr17 <- read_csv(here::here("data", "raw", "whr", "WHR2017.csv")) %>% clean_names()
whr   <- read.csv(here::here("data", "raw", "whr", "whr_panel.csv"))
census <- read_rds(here::here("data", "final", "census.RDS"))  

# Create vars for Intro to R session
v1 <- c(1,2,3,4,5)
v2 <- 1:5
df1 <- data.frame(v1, v2)
str_vec <- c("R", "Python", "SAS", "Excel", "Stata")
inc_below_avg <- whr$happiness_score < mean(whr$happiness_score)

# Create vars for R programming practices session
zscore <- function(x) {
  mean <- mean(x, na.rm = T)
  sd   <- sd(x, na.rm = T)
  z    <- (x - mean)/sd
  return(z)
}
```


```{r addition, exercise=TRUE}

```

